# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_auto_20190419_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='flag',
            field=models.CharField(default='1', max_length=10, verbose_name='权限标识符'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.IntegerField(unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.IntegerField(verbose_name='电话号码'),
        ),
    ]
