# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-23 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_auto_20190422_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='sex',
            field=models.CharField(default='男', max_length=50, verbose_name='楼房性别'),
        ),
    ]
