# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-23 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_auto_20190423_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default='18', verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.CharField(default='/static/dormitory/avatar/avatar08.jpg', max_length=255, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.IntegerField(null=True, verbose_name='电话号码'),
        ),
    ]
