# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0007_auto_20190423_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(max_length=11, null=True, verbose_name='电话号码'),
        ),
    ]
