# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-25 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0009_repairs_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairs',
            name='flag',
            field=models.CharField(default='0', max_length=50, verbose_name='维修状态'),
        ),
    ]
