# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-25 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0010_auto_20190425_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='anonymity',
            field=models.CharField(max_length=5, null=True, verbose_name='是否匿名'),
        ),
    ]
